import React, { useState, useEffect } from 'react';
import { Printer, ArrowLeft, Truck } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { fetchAPI } from '../utils/api';

interface AdminFleetReportProps {
  onClose: () => void;
}

export const AdminFleetReport: React.FC<AdminFleetReportProps> = ({ onClose }) => {
  const { t } = useTranslation();
  const [loading, setLoading] = useState(false);
  const [fleetData, setFleetData] = useState<any>(null);

  const loadData = async () => {
    setLoading(true);
    try {
      const res = await fetchAPI('/analytics/fleet');
      setFleetData(res);
    } catch (err) {
      console.error(err);
      alert('Failed to load fleet data.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  const getStatusCount = (status: string) => {
    if (!fleetData || !fleetData.fleetStatus) return 0;
    const item = fleetData.fleetStatus.find((f: any) => f._id === status);
    return item ? item.count : 0;
  };

  const available = getStatusCount('AVAILABLE');
  const rented = getStatusCount('RENTED');
  const maintenance = getStatusCount('MAINTENANCE');
  const total = available + rented + maintenance;
  const activePct = total > 0 ? Math.round(((available + rented) / total) * 100) : 0;

  return (
    <div className="admin-modal-overlay" style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(15, 23, 42, 0.8)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, backdropFilter: 'blur(4px)' }}>
      <div className="admin-modal-content" style={{ width: '850px', maxHeight: '90vh', backgroundColor: '#f8fafc', borderRadius: '16px', display: 'flex', flexDirection: 'column', overflow: 'hidden', boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)' }}>
        
        {/* Controls Header (No Print) */}
        <div className="no-print" style={{ padding: '24px 32px', backgroundColor: 'white', borderBottom: '1px solid #e2e8f0', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '18px', fontWeight: 800, color: '#0f172a' }}>
            <ArrowLeft size={20} /> {t('adminAnalytics.close', 'Close')}
          </button>
          
          <button 
            onClick={() => window.print()} 
            style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 20px', backgroundColor: '#0f172a', color: 'white', border: 'none', borderRadius: '8px', fontSize: '14px', fontWeight: 700, cursor: 'pointer' }}
          >
            <Printer size={18} /> {t('adminAnalytics.printReport', 'Print Report')}
          </button>
        </div>

        {/* Printable Area */}
        <div style={{ padding: '40px', overflowY: 'auto', flex: 1, backgroundColor: '#f1f5f9' }}>
          {loading ? (
            <div style={{ textAlign: 'center', padding: '40px', color: '#64748b' }}>{t('adminAnalytics.generatingReport', 'Generating Report...')}</div>
          ) : (
            <div id="printable-document" className="report-printable-area" style={{ background: 'white', padding: '24px', borderRadius: '8px', boxShadow: '0 4px 12px rgba(0,0,0,0.05)', color: '#0f172a' }}>
              
              {/* Report Header */}
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '24px', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '48px', borderBottom: '2px solid #0f172a', paddingBottom: '24px' }}>
                <div>
                  <h2 style={{ fontSize: '28px', fontWeight: 900, color: '#4d7c0f', margin: 0, letterSpacing: '2px' }}>THE GRANJA</h2>
                  <h2 style={{ fontSize: '28px', fontWeight: 900, color: '#4d7c0f', margin: 0, marginTop: '-4px', letterSpacing: '2px' }}>XTREME</h2>
                  <div style={{ fontSize: '12px', color: '#64748b', marginTop: '8px', fontWeight: 600, letterSpacing: '1px' }}>{t('adminAnalytics.fleetReportTitle', 'FLEET UTILIZATION REPORT')}</div>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ fontSize: '18px', fontWeight: 800, color: '#0f172a', marginBottom: '8px' }}>{t('adminAnalytics.currentOps', 'Current Operations Status')}</div>
                  <div style={{ fontSize: '13px', color: '#475569' }}>{t('adminAnalytics.generated', 'Generated:')} {new Date().toLocaleString()}</div>
                  <div style={{ fontSize: '13px', color: '#475569' }}>{t('adminAnalytics.generatedBy', 'Generated By: Admin System')}</div>
                </div>
              </div>

              {/* Summary Metrics */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))', gap: '24px', marginBottom: '48px', backgroundColor: '#f8fafc', padding: '24px', borderRadius: '12px', border: '1px solid #e2e8f0' }}>
                <div>
                  <div style={{ fontSize: '12px', fontWeight: 700, color: '#64748b', textTransform: 'uppercase', marginBottom: '8px' }}>{t('adminAnalytics.totalFleetSize', 'Total Fleet Size')}</div>
                  <div style={{ fontSize: '32px', fontWeight: 900, color: '#0f172a' }}>{total}</div>
                </div>
                <div>
                  <div style={{ fontSize: '12px', fontWeight: 700, color: '#64748b', textTransform: 'uppercase', marginBottom: '8px' }}>{t('adminAnalytics.currentlyRented', 'Currently Rented')}</div>
                  <div style={{ fontSize: '32px', fontWeight: 900, color: '#0284c7' }}>{rented}</div>
                </div>
                <div>
                  <div style={{ fontSize: '12px', fontWeight: 700, color: '#64748b', textTransform: 'uppercase', marginBottom: '8px' }}>{t('adminAnalytics.inMaintenance', 'In Maintenance')}</div>
                  <div style={{ fontSize: '32px', fontWeight: 900, color: '#ef4444' }}>{maintenance}</div>
                </div>
                <div>
                  <div style={{ fontSize: '12px', fontWeight: 700, color: '#64748b', textTransform: 'uppercase', marginBottom: '8px' }}>{t('adminAnalytics.operationalPct', 'Operational %')}</div>
                  <div style={{ fontSize: '32px', fontWeight: 900, color: '#16a34a' }}>{activePct}%</div>
                </div>
              </div>

              {/* Data Table */}
              <div style={{ marginBottom: '16px', fontSize: '16px', fontWeight: 800, color: '#0f172a', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <Truck size={20} color="#4d7c0f" /> {t('adminAnalytics.mostRented', 'Most Rented Vehicles')}
              </div>
              <div style={{ overflowX: 'auto', marginBottom: '48px' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
                <thead>
                  <tr style={{ borderBottom: '2px solid #cbd5e1' }}>
                    <th style={{ padding: '12px 16px', fontSize: '13px', fontWeight: 800, color: '#334155' }}>{t('adminAnalytics.vehicleModelName', 'Vehicle Model / Name')}</th>
                    <th style={{ padding: '12px 16px', fontSize: '13px', fontWeight: 800, color: '#334155', textAlign: 'right' }}>{t('adminAnalytics.totalAllTimeRentals', 'Total All-Time Rentals')}</th>
                  </tr>
                </thead>
                <tbody>
                  {!fleetData?.mostRented || fleetData.mostRented.length === 0 ? (
                    <tr><td colSpan={2} style={{ padding: '24px', textAlign: 'center', color: '#64748b' }}>{t('adminAnalytics.noVehicleData', 'No vehicle data available.')}</td></tr>
                  ) : (
                    fleetData.mostRented.map((row: any, idx: number) => (
                      <tr key={idx} style={{ borderBottom: '1px solid #f1f5f9', backgroundColor: idx % 2 === 0 ? 'white' : '#f8fafc' }}>
                        <td style={{ padding: '16px', fontSize: '14px', color: '#0f172a', fontWeight: 700 }}>
                          {row.name} {row.model}
                        </td>
                        <td style={{ padding: '16px', fontSize: '14px', color: '#0284c7', fontWeight: 800, textAlign: 'right' }}>
                          {row.count} {t('adminAnalytics.times', 'times')}
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
              </div>

              {/* Signatures */}
              <div style={{ marginTop: '64px', display: 'flex', justifyContent: 'space-between', borderTop: '1px solid #e2e8f0', paddingTop: '32px' }}>
                <div>
                  <div style={{ fontSize: '11px', color: '#64748b', fontWeight: 700, letterSpacing: '1px' }}>{t('adminAnalytics.preparedFor', 'PREPARED FOR')}</div>
                  <div style={{ fontSize: '16px', color: '#0f172a', fontWeight: 800, marginTop: '4px' }}>{t('adminAnalytics.fleetMgmt', 'FLEET MANAGEMENT')}</div>
                  <div style={{ fontSize: '12px', color: '#94a3b8', fontStyle: 'italic', marginTop: '4px' }}>The Granja Xtreme</div>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ fontSize: '11px', color: '#64748b', fontWeight: 700, letterSpacing: '1px' }}>{t('adminAnalytics.reportHash', 'REPORT AUTHENTICITY HASH')}</div>
                  <div style={{ fontSize: '12px', color: '#0f172a', fontFamily: 'monospace', marginTop: '4px' }}>FLT-{Math.random().toString(36).substring(2, 10).toUpperCase()}</div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
